# Generated by Django 3.2.4 on 2021-06-18 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='importingrecord',
            name='num',
            field=models.IntegerField(blank=True, db_column='Num', null=True),
        ),
    ]
